### PR TITLE
remove bugs

### PR DESCRIPTION
**Pull request by halalsandwich**
👍

### CODE REVIEW

**Comment by xbhl** [comment]
I honestly agree with this PR, it optimizes a lot of buggy code to actually suite proper Python syntax.

**Comment by verticalsync** [comment]
+rep

**Comment by Euro-pol** [comment]
lgtm

**Comment by Cloudzik1337** [comment]
Lmao, ye code is buggy af, and it's even mentioned in the readme. However, remember you don't have to use it, lmao. I've created a better and functional version for myself, and for now, I'm not planning on posting it on GitHub. I have other projects that bother me more than this nuker.

**Pull request closed without merging**
